# Archive associations
apps: {
  "application/gzip" = apps;
  "application/vnd.ms-cab-compressed" = apps;
  "application/vnd.rar" = apps;
  "application/x-7z-compressed" = apps;
  "application/x-archive" = apps;
  "application/x-bcpio" = apps;
  "application/x-bzip" = apps;
  "application/x-bzip-compressed-tar" = apps;
  "application/x-cd-image" = apps;
  "application/x-compress" = apps;
  "application/x-compressed-tar" = apps;
  "application/x-cpio" = apps;
  "application/x-cpio-compressed" = apps;
  "application/x-iso9660-appimage" = apps;
  "application/x-lha" = apps;
  "application/x-lrzip-compressed-tar" = apps;
  "application/x-lz4-compressed-tar" = apps;
  "application/x-lzip-compressed-tar" = apps;
  "application/x-lzma" = apps;
  "application/x-lzma-compressed-tar" = apps;
  "application/x-rar" = apps;
  "application/x-source-rpm" = apps;
  "application/x-sv4cpio" = apps;
  "application/x-sv4crc" = apps;
  "application/x-tar" = apps;
  "application/x-tarz" = apps;
  "application/x-tzo" = apps;
  "application/x-xar" = apps;
  "application/x-xz" = apps;
  "application/x-xz-compressed-tar" = apps;
  "application/x-zstd-compressed-tar" = apps;
  "application/zip" = apps;
  "application/zstd" = apps;
}
