[project]
name = "flowgenius"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "bbaserdem", email = "baserdemb@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
flowgenius = "flowgenius:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
